= Diplomarbeits Ideen
Stevan Vlajic
1.0.0, {docdate}: Softwareentwicklung
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:experimental:
:hide-uri-scheme:

//Need this blank line after ifdef, don't know why...

// print the toc here (not at the default position)
//toc::[]

== Connect together
* Eine App Mobile-App aufgebaut wie Tinder, um sich mit Menschen in einer einstellbaren Distanz zu verbinden und diese kennen zu lernen.
* Funktionalitäten:
** Chat-System
** Tinder Match-funktionalität
** General Settings
** Genaue locations schicken
** Announcements -> treffen vereinbaren
** Öffentliche Events finden
** ETC...
** Lokale in der Nähe

* Technologien:
*** Quarkus / Anderes Backend / Next JS / Svelete KIT
*** Front-End Framework
*** APP
*** Beispielsweise Twilio API's

== Lost & Found

* Eine Web-App gemacht zum finden Verlorener Gegenstände.
* Funktionalität:
** Posts werden erstellt mit der Beschreibung der Sachen und vlt Foto (wenn vorhanden) mit locations, in welchen man sich befunden hat als man den Gegenstand noch hatte
** Chat-Funktionalitaet
** Reagieren auf Posts mit auto-locations
** Up Vote System
** Filterung nach datum
** Push notifications  -> wenn in der Nähe von den eingegebenen locations
** AI tool, welches versucht die location anhand von den durch ein chat-system mitgegebenen Informationen, die Personen auf die richtige Fährte zu führen


== Event Organisierung

* Eine webapp in welcher sich Events erstellen lassen, welche durch tags verschiedenen Usern angezeigt werden
* Funktionalität:
** Events können erstellt werden, diese werden dann von den Usern abgerufen.
** Man kann sich zu Events eintrage
** Organisatoren können einsehen wer an welchen Events teilnimmt
** Smarter Platzvorschlag
** Angebote können von Firmen erstellt werden, für Plätze mit Preisen
** Events könne direkt gebucht werden
** Eingegebene Events werden überprüft -> Rollen werden festgelegt -> Appointments für Rollen
** Buchungssystem fürs zur Verfügung von Eventplätzen durch Firmen
** Automatic Mail-Formatierug für richtige Businessmail -> KI


== Rabbidly
* Is klar

== UMT (Integration of Untis, Moodle, and Teams)

=== Why?

There are too many tools we get information from.
The idea is to fusion their strengths all to one product 
to decrease complexity and increase working speed.

=== Brainstorming

The Untis interface lacks aesthetic appeal and fails to deliver optimal user experience. 
Moreover, Untis lacks a seamless method for exporting tests/exams for easy integration into other calendars or as tasks (CSV) in platforms like Notion.

Moodle is primarily employed in our school to organize homework and lecture materials into distinct sections. 
However, Moodle's user interface is perplexing and overly complicated. 
The sole necessity is different subject-specific rooms, yet Moodle offers more than required, which increases complexity. 
Teachers only need to oversee the rooms and verify student attendance.

*Issues with Moodle include:*

* Displaying only the upload date of material to the course, not when it was published to group members, which doesn't make any sense at all.
  * Lack of awareness regarding new publications until communicated by the course administrator.
* Not automatically featuring every task on the homepage, leading to the inconvenience of manually checking for missing todos.

Teams, on the other hand, is satisfactory. It enables chat within teams, task management, one-on-one communication, and provides a calendar and file upload capabilities. 
Essentially, Teams encompasses the functionalities of both Untis and Moodle.
Teams even obviates the need for an external FTP server (ANOTHER SOURCE OF DOCUMENTS. ARE YOU ACTUALLY INSANE?), allowing the upload of files up to 250GB and a total storage capacity of 25TB (https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams[*teams-limitations*]).

=> nahh (just don't use untis and moodle (and discord and ...), use teams instead)
